version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pde_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-product_data_explorer}
    ports:
      - "5433:5432"
    volumes:
      - pde_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pde_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pde_postgres_data:
